# Generated by Django 4.2.3 on 2023-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('cost', models.IntegerField()),
                ('dateTimeOfPosting', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_image/')),
            ],
            options={
                'ordering': ['dateTimeOfPosting'],
            },
        ),
    ]
