# Generated by Django 4.2.3 on 2023-09-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='adress',
        ),
    ]
