# Generated by Django 4.2.3 on 2023-09-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0002_rename_address_users_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='adress',
            new_name='address',
        ),
    ]
